name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Шаг 3: Сборка и загрузка образа для бекенда
      - name: Build and push backend
        run: |
          docker build -t sweetie059/dotsocialnetworkserver:latest -f dotSocialNetwork.Server/Dockerfile .
          docker push sweetie059/dotsocialnetworkserver:latest

      # Шаг 4: Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install sshpass

      # Шаг 5: Check if docker-compose.yml exists
      - name: Check if docker-compose.yml exists
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            ls -l /home/dotSocialNetwork/docker-compose.yml
          "

      # Шаг 6: Print current directory
      - name: Print current directory
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/dotSocialNetwork && pwd
          "

      # Шаг 7: Print docker-compose.yml content
      - name: Print docker-compose.yml content
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cat /home/dotSocialNetwork/docker-compose.yml
          "

      # Шаг 8: Deploy to server using Password
      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/dotSocialNetwork &&
            docker-compose pull &&
            docker-compose up -d
          "