name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Шаг 3: Сборка и загрузка образа для бекенда
      - name: Build and push backend
        run: |
          docker build -t sweetie059/dotsocialnetworkserver:latest -f dotSocialNetwork.Server/Dockerfile .
          docker push sweetie059/dotsocialnetworkserver:latest

      # Шаг 4: Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install sshpass

      # Шаг 5: Stop and Remove Container
      - name: Stop and Remove Container
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker stop dotsocialnetworkserver || true
            docker rm dotsocialnetworkserver || true
          "

      # Шаг 6: Run Container
      - name: Run Container
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker run -d --name dotsocialnetworkserver -p 80:65311 -p 5020:5020 sweetie059/dotsocialnetworkserver:latest
          "