name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Шаг 3: Сборка и загрузка образа для бекенда
      - name: Build and push backend
        run: |
          docker build -t sweetie059/dotsocialnetworkserver:latest -f dotSocialNetwork.Server/Dockerfile .
          docker push sweetie059/dotsocialnetworkserver:latest

      # Шаг 4: Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install sshpass

      # Шаг 5: Deploy to server using Password (without docker-compose)
      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            # Stop and remove existing container (if it exists)
            docker stop dotsocialnetworkserver || true && docker rm dotsocialnetworkserver || true

            # Run the new container
            docker run -d --name dotsocialnetworkserver \
              -p 80:80 \ # Replace with your port mapping
              # -e ENV_VAR=value # Add environment variables if needed
              sweetie059/dotsocialnetworkserver:latest
          "