name: Build and Deploy Containers

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub (or your container registry)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Server container
      - name: Build and push Server container
        working-directory: ./dotSocialNetwork.Server
        run: |
          docker build . -t sweetie059/dotsocialnetwork-server:latest
          docker push sweetie059/dotsocialnetwork-server:latest

      # Build and push Client container
      - name: Build and push Client container
        working-directory: ./dotsocialnetwork.client
        run: |
          docker build . -t sweetie059/dotsocialnetwork-client:latest
          docker push sweetie059/dotsocialnetwork-client:latest

      # Deploy to server via SSH with password
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Pull and restart Server container
            docker pull sweetie059/dotsocialnetwork-server:latest
            docker stop dotsocialnetwork-server || true
            docker rm dotsocialnetwork-server || true
            docker run -d --name dotsocialnetwork-server -p 5020:5020 sweetie059/dotsocialnetwork-server:latest

            # Pull and restart Client container
            docker pull sweetie059/dotsocialnetwork-client:latest
            docker stop dotsocialnetwork-client || true
            docker rm dotsocialnetwork-client || true
            docker run -d --name dotsocialnetwork-client -p 80:80 sweetie059/dotsocialnetwork-client:latest